import crypto from "node:crypto";
import { User } from "./db";

export class PasswordlessClient {
  constructor(private apiUrl: string, private apiSecret: string) {}

  async register(
    email: string,
    name: string
  ): Promise<{ token: string; userId: string }> {
    const userId = crypto.randomUUID();

    const payload = {
      userId, // A WebAuthn User Handle, which should be generated by your application. Max. 64 bytes.
      displayname: name, // A human-palatable name for the account, which should be chosen by the user.
      username: email, // A username used for user authentication, should be chosen by the user.
      aliases: [email],
      attType: "None", // WebAuthn attestation conveyance. Can be "none" (default), "direct", or "indirect".
      authType: "platform", // WebAuthn authenticator attachment modality. Can be "platform" (default), which triggers client device-specific options Windows Hello, FaceID, or TouchID, or "cross-platform", which triggers roaming options like security keys.
      userVerification: "preferred", // Whether the relying party requires locally-invoked authorization for the operation. Can be "preferred" (default), "required", or "optional".
      // expiresAt: "3023-08-01T14:43:03Z", // Timestamp (UTC) when the registration token should expire. By default, current time + 120 seconds.
    };

    const response = await fetch(`${this.apiUrl}/register/token`, {
      method: "POST",
      body: JSON.stringify(payload),
      headers: {
        ApiSecret: this.apiSecret,
        "Content-Type": "application/json",
      },
    });

    if (response.status > 299) {
      console.error(response.status, await response.text());
      throw new Error("Something happened when calling passwordless");
    }

    const token = await response.text();
    // const token = "something fake";

    return { token, userId };
  }

  async login(token: string): Promise<string | undefined> {
    const response = await fetch(`${this.apiUrl}/signin/verify`, {
      method: "POST",
      body: JSON.stringify({ token }),
      headers: {
        ApiSecret: this.apiSecret,
        "Content-Type": "application/json",
      },
    });

    if (response.status > 299) {
      console.error(
        "Something happened when calling passwordless.login",
        token,
        response.status,
        await response.text()
      );
      throw new Error("Something happened when calling passwordless");
    }

    const body = await response.json();

    if (body.success) {
      return body.userId;
    } else {
      console.warn("Sign in failed.", body);
      return undefined;
    }
  }

  async getCredentials(userId: string): Promise<unknown[]> {
    const response = await fetch(
      `${this.apiUrl}/credentials/list?userId=${userId}`,
      {
        method: "GET",
        headers: {
          ApiSecret: this.apiSecret,
          "Content-Type": "application/json",
        },
      }
    );

    if (response.status > 299) {
      console.error(
        "Something happened when calling passwordless.getCredentials",
        response.status,
        await response.text()
      );
      throw new Error("Something happened when calling passwordless");
    }

    const body = await response.json();
    return body;
  }

  async createCredential(user: User): Promise<{ token: string }> {
    const payload = {
      user: user.userId, // A WebAuthn User Handle, which should be generated by your application. Max. 64 bytes.
      displayname: user.name, // A human-palatable name for the account, which should be chosen by the user.
      username: user.email, // A username used for user authentication, should be chosen by the user.
      aliases: [user.email],
      attType: "None", // WebAuthn attestation conveyance. Can be "none" (default), "direct", or "indirect".
      authType: "platform", // WebAuthn authenticator attachment modality. Can be "platform" (default), which triggers client device-specific options Windows Hello, FaceID, or TouchID, or "cross-platform", which triggers roaming options like security keys.
      userVerification: "preferred", // Whether the relying party requires locally-invoked authorization for the operation. Can be "preferred" (default), "required", or "optional".
      // expiresAt: "3023-08-01T14:43:03Z", // Timestamp (UTC) when the registration token should expire. By default, current time + 120 seconds.
    };

    const response = await fetch(`${this.apiUrl}/register/token`, {
      method: "POST",
      body: JSON.stringify(payload),
      headers: {
        ApiSecret: this.apiSecret,
        "Content-Type": "application/json",
      },
    });

    if (response.status > 299) {
      console.error(response.status, await response.text());
      throw new Error("Something happened when calling passwordless");
    }

    const token = await response.text();
    // const token = "something fake";

    return { token };
  }
}
